app.js, controllers/user.controllers.js, middlewares/auth.middleware.js, package.json, repositories/user.repository.js, routes/index.js, routes/user.routes.js, services/user.service.js
=> feature: 회원가입, 로그인, 로그아웃 구현

controllers/company.controllers.js, db/index.js, db/models/company.js, db/models/inquiry.js, db/models/post.js, db/models/review.js, db/models/schedule.js, repositories/company.repository.js, repositories/index.js, routes/company.routes.js, routes/index.js, services/company.service.js
- company 생성 API 추가
- company 전체 조회 API 추가
- company 상세 조회 API 추가
- company 수정 API 추가
- company 삭제 API 추가
- 머지 후 해당 로그인 유저가 owner인지 확인하는 코드 추가해야함.
=> feat: company

controllers/trainer.controllers.js, repositories/company.repository.js, repositories/index.js, repositories/trainer.repository.js, routes/index.js, routes/trainer.routes.js, services/trainer.service.js
=> fix : trainer api 완료

app.js, controllers/user.controllers.js, db/models/user.js, db/relations/company.relation.js, middlewares/auth.middleware.js, public/kakao.html, repositories/user.repository.js, routes/user.routes.js, services/user.service.js
로그인 테스트까지 완료
추후 , 로컬 로그아웃과 똑같이 소셜도 로그아웃 되는지 
프론트 구현 후 테스트 가능
=> feat:소셜로그인 카카오톡 완료

controllers/company.controllers.js, public/from_kakaoMap.html, public/kakaoMap.html, repositories/company.repository.js, services/company.service.js
- Kakao지도 company에 따른 업체 이름, 주소, companyId 연동한 지도 띄우기.
=> feat : KakaoMap 업체 연동

controllers/company.controllers.js, controllers/trainer.controllers.js, controllers/user.controllers.js, db/models/company.js, middlewares/auth.middleware.js, repositories/company.repository.js, repositories/trainer.repository.js, repositories/user.repository.js, routes/company.routes.js, routes/trainer.routes.js, services/calender.service.js, services/company.service.js, services/trainer.service.js
-  company,trainer 테스트 완료
- 추후 어드민 계정 권한 수정 필요
=> refactor:company,trainer 테스트 완료

controllers/contract.controllers.js, repositories/company.repository.js, repositories/contract.repository.js, repositories/trainer.repository.js, routes/contract.routes.js, services/company.service.js, services/contract.service.js, services/inquiry.service.js, services/report.service.js
- getContractId 메소드 추가 => contract.repository.js 
- getExistTrainerId 메소드 추가 => trainer.repository.js 
- 계약 삭제 코드 수정 (admin 삭제 권한)
=> fix: 계약 CRUD 수정 및 피드백 반영

public/css/OwnerCompany/getOwnerCompany.css, public/css/OwnerCompany/setOwnerCompany.css, public/js/OwnerCompany/getOwnerCompany.js, public/templates/OwnerCompany/getOwnerCompany.html, public/templates/OwnerCompany/putOwnerCompany.html, public/templates/OwnerCompany/setOwnerCompany.html
html
- <li> Owner에 맞게 버튼 수정 및 링크 조정
css
- <li> css 추가
-  getOwnerCompany 리뷰 추가
js
- getOwnerCompany => 가시성을 위한 업체명, 주소명 박스 내부로 이동
- 기존의 companyName과 map을 불러오던 로직을 지우고
- infoBox.innerHTML 에 함께 삽입
=> fix : Owner 관련 html, css, js

public/js/company/getDetailCompany.js, public/templates/OwnerCompany/getOwnerCompany.html, public/templates/company/getUserDetailCompany.html
- 최하단 kakaoMap 확인 가능합니다.
- getDetailCompany 업체 상세 조회 부분에 추가 하였습니다.
- getUserDetailCompany.html head에 추가된 script는 kakaoMap SDK를 불러옵니다. defer 추가하면 기능이 작동하지 않습니다.
- getOwnerCompany.html 등록된 트레이너, 리뷰가 없을 경우 알 수 있도록 안내문을 표시하였습니다.
=> feat : getDetailCompany화면 조회했을 때 주소에 따른 kakaoMap 구현 

app.js, controllers/company.controllers.js, controllers/trainer.controllers.js, middlewares/awsS3.middleware.js, public/js/OwnerCompany/getOwnerCompany.js, public/js/OwnerCompany/setOwnerCompany.js, public/templates/OwnerCompany/getOwnerCompany.html, public/templates/OwnerCompany/setOwnerCompany.html, routes/company.routes.js, routes/trainer.routes.js
현재 다중업로드 가능 .
이후 , 파일의 갯수제한 , 용량제한 등 설정 추가할 예정
=> fix:aws s3 다중업로드

controllers/contract.controllers.js, db/db.js, db/models/contract.js, public/css/modal.css, public/js/contract/createUserContract.js, public/js/contract/getcontract.js, public/templates/company/getUserDetailTrainer.html, repositories/contract.repository.js, routes/contract.routes.js, services/contract.service.js
- contract table 에 ptNumber column 추가
- contract 생성 시 ptNumber 받아오도록 수정
- ptNumber 값은 0 ~ 100 의 범위만 가능하도록 예외 처리
- 프론트에서 number 타입만 보낼 수 있도록 설정 type="number"
- contract의 ptNumber update하는 api 추가
- 해당 api 요청 시 ptNumber가 -1
- ptNumber가 0보다 작을 경우 예외 처리
- ptNumber update api는 trainer가 직접 하도록 front 구현
( trainer가 마음대로 줄일 수 있는 서비스적인 부분은 문제가 될 수 있지만 신고 및 문의 기능이 존재하니 충분히 대처 가능하다고 판단 )
=> fix : contract

db/models/company.js, public/css/OwnerCompany/getOwnerCompany.css, public/css/OwnerCompany/setOwnerCompany.css, public/js/OwnerCompany/getOwnerCompany.js, public/templates/OwnerCompany/putOwnerCompany.html, public/templates/OwnerCompany/setOwnerCompany.html
트레이너 중첩 -> 정상적으로 보이게 수정 완료
업체_트레이너 -> CSS 수정
업체 등록, 수정 e.g. 멘트 수정
Company db -> Time 타입 String으로 변환
=> fix : Company에서 트레이너가 등록시 단 한명만 보이는 문제 해결.

.github/ci.yml
- 미완성
- 테스트 코드 및 배포 서버 구성 후 수정 할 예정
=> feat: CICD

db/models/company.js, package.json, public/js/OwnerCompany/getOwnerCompany.js, public/js/company/getDetailCompany.js, public/js/company/getDetailTrainer.js, public/templates/OwnerCompany/getOwnerCompany.html, public/templates/company/getUserDetailCompany.html
유저 화면단에서 헬스장 디테일 페이지 이미지 url만 뜨는 현상 고침
이미지 리사이징 하다가 만거 함께 올라가있음
=> fix:user-company image error fix

.github/workflows/docker.yml, public/templates/chat/getChatRoom.html
=> fix: error

public/templates/chat/getChatRoom.html
=> fix: chatRoom.css

.github/workflows/docker.yml
=> fix: version_label

package.json
=> RDBMS change

.github/workflows/docker.yml
=> version_label change

controllers/calender.controllers.js, controllers/company.controllers.js, controllers/trainer.controllers.js, middlewares/awsS3.middleware.js, package.json, services/calender.service.js
[라이브러리 의존성문제 해결 이미지 리사이징 해결](https://github.com/chatDiet/chatDiet/pull/142)
=> fix: multer-s3-transform image resizing sharp error fix

db/models/trainer.js, public/js/contract/createUserContract.js, public/js/payment/kakaoPayment.js, public/templates/trainer/createTrainer.html, public/templates/trainer/updateTrainerInfo.html
- ptAmount를 string형식이 아닌 intger형식으로 작성하도록 수정
- if (Contracts.length > 0)의 조건이 모든 계약에 대한 조건으로 설정되어 다른 트레이너와의 계약에서도 문제 발생
-  일치하는 트레이너 아이디에 대해서 필터링 하여 matchingContracts에 담아서 if (matchingContracts.length > 0)로 수정함.
=> fix:결제기능 에러 수정 및 일부 로직 수정

controllers/trainer.controllers.js, public/js/trainer/createTrainer.js, public/js/trainer/getTrainerInfo.js, public/templates/trainer/createTrainer.html, public/templates/trainer/updateTrainerInfo.html, repositories/trainer.repository.js, services/trainer.service.js
-트레이너 생성 및 정보 수정시 ptAmount값이 string으로 넘어오는 값 예외처리 완료
- ptAmount값이 0일때 alert추가 (문자열 1자리가 입력 가능한 상태이며 문자열 입력시 ptAmount는 0으로 설정됨)
=> fix:프론트에서 전달되는 ptAmount 값 수정

repositories/company.repository.js, repositories/post.repository.js, services/company.service.js
- 기존 company 조회 , trainer 조회 별도 요청
-  company 조회 시 join 을 통해 한번에 불어오도록 수정
- 기존 post 조회 , comment 조회 , userInfo(ustName) 조회 별도 요청
- post 조회 시 join 을 통해 한번에 불러오도록 수정
- Front 작업은 하지 않음
=> Fix: oneGetCompany, getPostId

repositories/company.repository.js, repositories/post.repository.js
- company service.js 중복적으로 예외처리 되는 부분 미들웨어 처리
=> fix: 중복 예외 처리 미들웨어 처리
